from sqlalchemy import Column, Integer, ForeignKey, BigInteger, String, Boolean, DateTime, Numeric, JSON, text
from sqlalchemy.dialects.postgresql import JSONB, ARRAY
from app.core.database import Base

class TelemetriaRouter15m(Base):
    __tablename__ = 'telemetria_router_15m'
    
    periodo_inicio = Column(DateTime, primary_key=True)
    periodo_fin = Column(DateTime)
    tenant_id = Column(BigInteger, ForeignKey('tenants.id'))
    cuenta_id = Column(Integer)
    linea_servicio_id = Column(Integer, ForeignKey('lineas_servicio.id'))
    dispositivo_id = Column(Integer, ForeignKey('dispositivos.id'))
    router_id = Column(BigInteger, ForeignKey('routers.id'), primary_key=True)
    primera_muestra = Column(DateTime)
    ultima_muestra = Column(DateTime)
    muestras_totales = Column(Integer)
    muestras_slots_15s = Column(Integer)
    muestras_esperadas = Column(Integer)
    cobertura_pct = Column(Numeric)
    offline_segundos_estimados = Column(Integer)
    wifi_uptime_segundos_max = Column(BigInteger)
    wifi_uptime_segundos_last = Column(BigInteger)
    software_version_last = Column(String)
    wifi_es_repetidor_last = Column(Boolean)
    wifi_saltos_controlador_max = Column(Integer)
    wifi_saltos_controlador_last = Column(Integer)
    wifi_bypass_last = Column(Boolean)
    internet_drop_rate_avg = Column(Numeric)
    internet_drop_rate_min = Column(Numeric)
    internet_drop_rate_max = Column(Numeric)
    internet_drop_rate_last = Column(Numeric)
    internet_latency_ms_avg = Column(Numeric)
    internet_latency_ms_min = Column(Numeric)
    internet_latency_ms_max = Column(Numeric)
    internet_latency_ms_last = Column(Numeric)
    pop_drop_rate_avg = Column(Numeric)
    pop_drop_rate_min = Column(Numeric)
    pop_drop_rate_max = Column(Numeric)
    pop_drop_rate_last = Column(Numeric)
    pop_latency_ms_avg = Column(Numeric)
    pop_latency_ms_min = Column(Numeric)
    pop_latency_ms_max = Column(Numeric)
    pop_latency_ms_last = Column(Numeric)
    dish_drop_rate_avg = Column(Numeric)
    dish_drop_rate_min = Column(Numeric)
    dish_drop_rate_max = Column(Numeric)
    dish_drop_rate_last = Column(Numeric)
    dish_latency_ms_avg = Column(Numeric)
    dish_latency_ms_min = Column(Numeric)
    dish_latency_ms_max = Column(Numeric)
    dish_latency_ms_last = Column(Numeric)
    clientes_total_avg = Column(Numeric)
    clientes_total_min = Column(Integer)
    clientes_total_max = Column(Integer)
    clientes_total_last = Column(Integer)
    clientes_2ghz_avg = Column(Numeric)
    clientes_2ghz_max = Column(Integer)
    clientes_2ghz_last = Column(Integer)
    clientes_5ghz_avg = Column(Numeric)
    clientes_5ghz_max = Column(Integer)
    clientes_5ghz_last = Column(Integer)
    clientes_ethernet_avg = Column(Numeric)
    clientes_ethernet_max = Column(Integer)
    clientes_ethernet_last = Column(Integer)
    wan_tx_bytes_delta = Column(BigInteger)
    wan_rx_bytes_delta = Column(BigInteger)
    wan_tx_bytes_last = Column(BigInteger)
    wan_rx_bytes_last = Column(BigInteger)
    rx_rate_2ghz_mbps_avg = Column(Numeric)
    rx_rate_2ghz_mbps_max = Column(Numeric)
    rx_rate_2ghz_mbps_last = Column(Numeric)
    tx_rate_2ghz_mbps_avg = Column(Numeric)
    tx_rate_2ghz_mbps_max = Column(Numeric)
    tx_rate_2ghz_mbps_last = Column(Numeric)
    signal_2ghz_avg = Column(Numeric)
    signal_2ghz_min = Column(Numeric)
    signal_2ghz_max = Column(Numeric)
    signal_2ghz_last = Column(Numeric)
    rx_rate_5ghz_mbps_avg = Column(Numeric)
    rx_rate_5ghz_mbps_max = Column(Numeric)
    rx_rate_5ghz_mbps_last = Column(Numeric)
    tx_rate_5ghz_mbps_avg = Column(Numeric)
    tx_rate_5ghz_mbps_max = Column(Numeric)
    tx_rate_5ghz_mbps_last = Column(Numeric)
    signal_5ghz_avg = Column(Numeric)
    signal_5ghz_min = Column(Numeric)
    signal_5ghz_max = Column(Numeric)
    signal_5ghz_last = Column(Numeric)
    muestras_con_alerta = Column(Integer)
    codigos_alerta = Column(ARRAY(String))
    fecha_calculo = Column(DateTime)

class TelemetriaRouterRt(Base):
    __tablename__ = 'telemetria_router_rt'
    
    id = Column(BigInteger, primary_key=True)
    tenant_id = Column(BigInteger, ForeignKey('tenants.id'))
    cuenta_id = Column(Integer)
    linea_servicio_id = Column(Integer, ForeignKey('lineas_servicio.id'))
    dispositivo_id = Column(Integer, ForeignKey('dispositivos.id'))
    router_id = Column(BigInteger, ForeignKey('routers.id'))
    fecha_hora_lectura = Column(DateTime)
    wifi_uptime_segundos = Column(BigInteger)
    software_version = Column(String)
    wifi_es_repetidor = Column(Boolean)
    wifi_saltos_controlador = Column(Integer)
    wifi_bypass = Column(Boolean)
    internet_drop_rate = Column(Numeric)
    internet_latency_ms = Column(Numeric)
    pop_drop_rate = Column(Numeric)
    pop_latency_ms = Column(Numeric)
    dish_drop_rate = Column(Numeric)
    dish_latency_ms = Column(Numeric)
    clientes_total = Column(Integer)
    clientes_2ghz = Column(Integer)
    clientes_5ghz = Column(Integer)
    clientes_ethernet = Column(Integer)
    wan_tx_bytes = Column(BigInteger)
    wan_rx_bytes = Column(BigInteger)
    rx_rate_2ghz_mbps = Column(Numeric)
    tx_rate_2ghz_mbps = Column(Numeric)
    signal_2ghz_min = Column(Numeric)
    signal_2ghz_max = Column(Numeric)
    signal_2ghz_avg = Column(Numeric)
    rx_rate_5ghz_mbps = Column(Numeric)
    tx_rate_5ghz_mbps = Column(Numeric)
    signal_5ghz_min = Column(Numeric)
    signal_5ghz_max = Column(Numeric)
    signal_5ghz_avg = Column(Numeric)
    codigos_alerta = Column(ARRAY(String))
    raw_json = Column(JSONB)
    fecha_registro_bd = Column(DateTime)

class TelemetriaTerminal15m(Base):
    __tablename__ = 'telemetria_terminal_15m'
    
    periodo_inicio = Column(DateTime, primary_key=True)
    periodo_fin = Column(DateTime)
    tenant_id = Column(BigInteger, ForeignKey('tenants.id'))
    cuenta_id = Column(Integer)
    linea_servicio_id = Column(Integer, ForeignKey('lineas_servicio.id'))
    dispositivo_id = Column(Integer, ForeignKey('dispositivos.id'), primary_key=True)
    primera_muestra = Column(DateTime)
    ultima_muestra = Column(DateTime)
    muestras_totales = Column(Integer)
    muestras_slots_15s = Column(Integer)
    muestras_esperadas = Column(Integer)
    cobertura_pct = Column(Numeric)
    offline_segundos_estimados = Column(Integer)
    downlink_mbps_avg = Column(Numeric)
    downlink_mbps_min = Column(Numeric)
    downlink_mbps_max = Column(Numeric)
    downlink_mbps_last = Column(Numeric)
    uplink_mbps_avg = Column(Numeric)
    uplink_mbps_min = Column(Numeric)
    uplink_mbps_max = Column(Numeric)
    uplink_mbps_last = Column(Numeric)
    ping_drop_rate_avg = Column(Numeric)
    ping_drop_rate_min = Column(Numeric)
    ping_drop_rate_max = Column(Numeric)
    ping_drop_rate_last = Column(Numeric)
    ping_latency_ms_avg = Column(Numeric)
    ping_latency_ms_min = Column(Numeric)
    ping_latency_ms_max = Column(Numeric)
    ping_latency_ms_last = Column(Numeric)
    obstruccion_avg = Column(Numeric)
    obstruccion_min = Column(Numeric)
    obstruccion_max = Column(Numeric)
    obstruccion_last = Column(Numeric)
    signal_quality_avg = Column(Numeric)
    signal_quality_min = Column(Numeric)
    signal_quality_max = Column(Numeric)
    signal_quality_last = Column(Numeric)
    uptime_segundos_max = Column(BigInteger)
    uptime_segundos_last = Column(BigInteger)
    h3_cell_id_last = Column(String)
    country_code_last = Column(String)
    in_territorial_waters_last = Column(Boolean)
    software_version_last = Column(String)
    segundos_hasta_reboot_last = Column(Integer)
    muestras_con_alerta = Column(Integer)
    codigos_alerta = Column(ARRAY(String))
    fecha_calculo = Column(DateTime)

class TelemetriaTerminalRt(Base):
    __tablename__ = 'telemetria_terminal_rt'
    
    id = Column(BigInteger, primary_key=True)
    tenant_id = Column(BigInteger, ForeignKey('tenants.id'))
    cuenta_id = Column(Integer)
    linea_servicio_id = Column(Integer, ForeignKey('lineas_servicio.id'))
    dispositivo_id = Column(Integer, ForeignKey('dispositivos.id'))
    fecha_hora_lectura = Column(DateTime)
    downlink_mbps = Column(Numeric)
    uplink_mbps = Column(Numeric)
    ping_drop_rate_avg = Column(Numeric)
    ping_latency_ms_avg = Column(Numeric)
    porcentaje_obstruccion = Column(Numeric)
    uptime_segundos = Column(BigInteger)
    signal_quality = Column(Numeric)
    h3_cell_id = Column(String)
    country_code = Column(String)
    in_territorial_waters = Column(Boolean)
    software_version = Column(String)
    segundos_hasta_reboot_update = Column(Integer)
    codigos_alerta = Column(ARRAY(String))
    raw_json = Column(JSONB)
    fecha_registro_bd = Column(DateTime)
